[project]
name = "moma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "mystmd>=1.7.1",
    "numpy>=2.4.1",
    "scipy>=1.17.0",
]
